apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ include "dnsconfiginjector.fullname" . }}-admission-create
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded   
  labels:
    app: {{ include "dnsconfiginjector.fullname" . }}-admission-create   
    {{- include "dnsconfiginjector.labels" . | nindent 4 }} 
spec:
  template:
    metadata:
      name:  {{ include "dnsconfiginjector.fullname" . }}-admission-create
      labels:
        {{- include "dnsconfiginjector.labels" . | nindent 8 }}
    spec:
      containers:
        - name: create
          image: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.3.0
          imagePullPolicy: IfNotPresent
          args:
            - create
            - --host={{ template "dnsconfiginjector.fullname" . }},{{ template "dnsconfiginjector.fullname" . }}.{{- .Release.Namespace -}}.svc
            - --namespace={{- .Release.Namespace }}
            - --secret-name={{ include "dnsconfiginjector.fullname" . }}-admission
          resources:
{{ toYaml .Values.admissionWebhooks.resources | indent 12 }}
      restartPolicy: OnFailure
      serviceAccountName: {{ include "dnsconfiginjector.fullname" . }}-admission
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
