apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "dnsconfiginjector.fullname" . }}-admission
  labels:
    app: {{ include "dnsconfiginjector.fullname" . }}
webhooks:
  - name: {{ include "dnsconfiginjector.fullname" . }}.{{ .Release.Namespace }}.svc
    clientConfig:
      service:
        name: {{ include "dnsconfiginjector.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
      caBundle: ""
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Ignore
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    namespaceSelector:
      matchLabels:
        dnsconfig-injector: enabled