apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ include "dnsconfiginjector.fullname" . }}-admission
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "dnsconfiginjector.labels" . | nindent 4 }}

